### ISSUE TITLE
PvP improvement 

### ISSUE THREAD

**Issue by Fabio1988** [na-ji/pvpoke-to-poracle#1]
Hy, some thoughts from users of my map, which are more familiar with PvP

> Generally not bad, but what I noticed, there are also legendaries. the first entry at pvpoke is registeel and that was also adopted so, it is the first in it, but of course this is meaningless 😅
with the super league it is so 3/30 de would be omitted.

> more problematic is the ultra league, there 10/30 fall away, so 1/3 😬

> the even bigger problem is, the result includes the number of pokémon that have the rank. But most of them are evolutions. Of these, some don't spawn at all, others extremely rarely. Many of them also need a top TM.
For example, instead of Swampert, Mudkip should be in the list. Instead of Trevenant (doesn't spawn), Phantump etc.

Any ideas to that thoughts of my users? :)

The last one could be solved by poracle, but don't know if it suggests also mudkip when only swampert is in list, I know it works the other way round :)

**Comment by na-ji** [comment]
Hello! Thank you for your feedback! 

> > Generally not bad, but what I noticed, there are also legendaries. the first entry at pvpoke is registeel and that was also adopted so, it is the first in it, but of course this is meaningless 😅
> > with the super league it is so 3/30 de would be omitted.
> 
> > more problematic is the ultra league, there 10/30 fall away, so 1/3 😬

I didn't think there were this many legendaries. I will make a filter for them. 

> the even bigger problem is, the result includes the number of pokémon that have the rank. But most of them are evolutions. Of these, some don't spawn at all, others extremely rarely. Many of them also need a top TM.
> For example, instead of Swampert, Mudkip should be in the list. Instead of Trevenant (doesn't spawn), Phantump etc.

I thought when you use the pvp ranking filter on Poracle, it would notify every pre-evolution too. There is even a template for displaying the evolution + upgrade cost to reach the pvp cut off. Or maybe I misunderstood the filtering 🤔

**Comment by Fabio1988** [comment]
What my user saw there was 3/30 legendaries, so yes not that much :)

Regarding evolution, I am not sure if poracle tracks also the base form if we only track an evolution. I know it works the other way round.

I am sure about tracking mudkip will notify about a pvp swampert.
But I am not sure about tracking swampert will notify about a mudkip spawning which is relevant as swampert in pvp :)

@jfberry could maybe help to clarify :)

**Comment by jfberry** [comment]
If you have evolution tracking on in config then you will get alerts on the base form when tracking an evolved form for pvp

**Comment by na-ji** [comment]
BTW, I just thought about something, should I filter out shadows too @Fabio1988?

**Comment by Fabio1988** [comment]
> BTW, I just thought about something, should I filter out shadows too @Fabio1988?

Hmm would make sense, they can not be caught from wild spawns :)
