### ISSUE TITLE
Reformat tracking list

### ISSUE THREAD

**Issue by Fabio1988** [na-ji/pvpoke-to-poracle#2]
https://github.com/na-ji/pvpoke-to-poracle/blob/a2efead203e3e461c335cd2e6ea223fc5b524bc2/top30great.txt#L1

Imo it would be easier to use following format:

```
!track 379 618 308 260 560 411 709 279 164 334 472 108 171 18 68 832 784 302 799 226 340 630 288 660 38 377 202 197 699 great1
```

That would be also compatible with Telegram usages and does have the same affect :)

**Comment by na-ji** [comment]
Hello ! I wasn't aware we could track many mons at once. I thought the only way is to use the batch commands. Thanks for the feedback.

**Comment by na-ji** [comment]
I just thought about something: this way won't work when tracking forms, no? For instance, for Galarian Stunfisk. I just found a way to set forms correctly, so I will have to think about how to implement it.

**Comment by Fabio1988** [comment]
For specific forms it would be a second tracking, right. But actually it's tracking all forms, true 🤔 

so you would have to separate trackings for forms, true :)

```
!track great1 6
!track great1 554 618 form:galarian
```
